name: Ci test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Get the working directory
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'          
          cache: "yarn"

      - name: Install all dependencies
        run: yarn

      - name: Install both modules
        run: yarn modules

      - name: Typescript check
        run: yarn ts-check

      - name: Build test
        run: yarn build
